name    'saz-sudo'
version '2.3.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage sudo configuration via Puppet'
project_page 'https://github.com/saz/puppet-sudo'
