name    'saz-sudo'
version '3.0.9'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage sudo configuration via Puppet'
dependency 'puppetlabs/stdlib', '>= 2.3.0'
project_page 'https://github.com/saz/puppet-sudo'
